/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AgentGrid: typeof import('./src/components/AgentGrid.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    ApprovalModal: typeof import('./src/components/ApprovalModal.vue')['default']
    AstItem: typeof import('./src/components/AstItem.vue')['default']
    DiffViewer: typeof import('./src/components/DiffViewer.vue')['default']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    EventList: typeof import('./src/components/EventList.vue')['default']
    NotifModal: typeof import('./src/components/NotifModal.vue')['default']
    RecoveryPanel: typeof import('./src/components/RecoveryPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatsGrid: typeof import('./src/components/StatsGrid.vue')['default']
  }
}
