/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AgentGrid: typeof import('./src/components/AgentGrid.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    ApprovalModal: typeof import('./src/components/ApprovalModal.vue')['default']
    AstItem: typeof import('./src/components/AstItem.vue')['default']
    EventList: typeof import('./src/components/EventList.vue')['default']
    NotifModal: typeof import('./src/components/NotifModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatsGrid: typeof import('./src/components/StatsGrid.vue')['default']
  }
}
